apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: helloopenshift
  name: hello-openshift
  namespace: myproject
spec:
  host: hello-openshift-default.192.168.0.10.nip.io
  to:
    kind: Service
    name: hello-openshift
    weight: 100
  wildcardPolicy: None