apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
spec:
  project: default
  source:
    repoURL: 'https://github.com/DonatoVerardi/hello-openshift'
    path: tekton
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true