apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: slow
  hostPath:
    path: /mnt/sda1/var/lib/minishift/openshift.local.volumes/pv/reports