apiVersion: apps/v1
kind: Deployment
metadata:
  name: gauge-taiko
  labels:
    app: gauge-taiko
    hello: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gauge-taiko
  template:
    metadata:
      labels:
        app: gauge-taiko
    spec:
      # Volumes used by this deployment
      serviceAccount: gauge

      volumes:
      - name: reports
        # This volume is based on PVC
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: gauge-taiko-reports-pv-claim
      - name: gauge-specs
        configMap:
          name: gauge-specs
      - name: gauge-tests
        configMap:
          name: gauge-tests
      - name: gauge-env
        configMap:
          name: gauge-env
      - name: gauge-package
        configMap:
          name: gauge-package
      containers:
      - name: gauge-taiko
        image: donatoverardi/gauge-taiko:v1.0.3
        volumeMounts:
        # Volume 'reports' is mounted to path '/gauge/reports'
        - name: reports
          mountPath: "/gauge/reports"
          readOnly: false
        - name: gauge-specs
          mountPath: /gauge/specs/CAM_example.spec
          subPath: CAM_example.spec
        - name: gauge-tests
          mountPath: /gauge/tests/step_implementation.js
          subPath: step_implementation.js
        - name: gauge-env
          mountPath: /gauge/env/default
        - name: gauge-package
          mountPath: /gauge/package.json
          subPath: package.json
