apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports
  labels:
    app: gauge-taiko
    hello: world
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /var/lib/minishift/openshift.local.volumes/pv/reports