apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./gauge-taiko-sa.yaml
- ./gauge-taiko-pv.yaml
- ./gauge-taiko-pvc.yaml
- ./gauge-taiko-deployment.yaml
- ./gauge-taiko-svc.yaml
- ./gauge-taiko-route.yaml
    