apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./gauge-taiko-sa.yaml
- ./gauge-taiko-pv.yaml
- ./gauge-taiko-pvc.yaml
- ./gauge-taiko-deployment.yaml
- ./nginx-deployment.yaml
- ./gauge-taiko-svc.yaml
- ./gauge-taiko-route.yaml


configMapGenerator:
  - name: my-server-block
    files:
      - ./files/my_server_block.conf
  - name: gauge-specs
    files:
      - ./files/CAM_example.spec
  - name: gauge-env
    files:
      - ./files/default.properties
      - ./files/headless.properties
      - ./files/js.properties
  - name: gauge-tests
    files:
      - ./files/step_implementation.js
  - name: gauge-package
    files:
      - ./files/package.json